### ISSUE TITLE
Functions Question 

### ISSUE THREAD

**Issue by mikejnpc** [traxm/Micro-Bitcoin-Collider#5]
Hello,

Can public keys  be loaded instead of addresses?  
If not can this function be added in future release? 
Have you had any positive results?

Thanks

**Comment by mikejnpc** [comment]
Also is there  a limit on how many entries ? 

Exception in thread "Thread-4" java.lang.StringIndexOutOfBoundsException: String index out of range: 0
        at java.lang.String.charAt(Unknown Source)
        at LoadAddresses.readLines(LoadAddresses.java:198)
        at LoadAddresses.initializeLookupAddresses(LoadAddresses.java:69)
        at LoadAddresses.run(LoadAddresses.java:32)

**Comment by calendulauda** [comment]
I would like to load address as well. But it would be better if there was opportunity to generate half of private key.  Lets say I have a piece of paper with half of private key and I now public address, but still generate all those variants in txt. gonna be way bigger than I can handle.
